const assert = require('node:assert/strict');
const E = require('../veldora-shell/VeldoraEvents.js');
const A = require('../veldora-shell/VeldoraApps.js');
const now = 10000;
const event = (overrides={}) => E.veldoraNormalize({id:'one',title:'Hello',...overrides},now);
assert.equal(event({trustLevel:'trusted',actions:['delete']}).trustLevel,'untrusted-application');
assert.deepEqual(event({actions:['delete']}).actions,[]);
assert.equal(event({ttl:Infinity}).expiresAt,15000);
assert.equal(event({ttl:1,progress:4}).expiresAt,11000);
assert.equal(event({progress:4}).progress,1);
assert.equal(event({body:'x'.repeat(3000)}).body.length,1200);
let history=E.veldoraInsert([],event());
history=E.veldoraInsert(history,event({title:'replacement'}));
assert.equal(history.length,1);
assert.equal(history[0].title,'replacement');
history=E.veldoraInsert(history,event({source:'Other'}));
assert.equal(history.length,2);
for(let i=0;i<150;i++) history=E.veldoraInsert(history,event({id:String(i)}));
assert.equal(history.length,100);
assert.equal(E.veldoraActive(history,16000,false,false,false),null);
for (const flags of [[true,false,false],[false,true,false],[false,false,true]]) assert.equal(E.veldoraActive(history,now,...flags),null);
assert.equal(E.veldoraActive([event({kind:'media'}),event({kind:'notification',id:'urgent'})],now,false,false,false).id,'urgent');
assert.equal(E.veldoraRemove([event()],'one').length,0);
assert.equal(E.veldoraRetained([event()],now+86400000).length,0);
const apps=[{id:'kitty',name:'Kitty'},{id:'org.mozilla.firefox',name:'Firefox',startupClass:'firefox'}];
const win=(cls,id)=>({lastIpcObject:{class:cls},address:id});
const groups=A.veldoraGroup(apps,['kitty','missing','kitty'],[win('kitty','a'),win('kitty','b'),win('firefox','c'),win('custom','d'),win('','e')]);
assert.equal(groups.length,4);
assert.equal(groups[0].windows.length,2);
assert.equal(groups[0].pinned,true);
assert.equal(groups[1].id,'org.mozilla.firefox');
assert.equal(groups[2].id,'window:custom');
assert.equal(groups[3].id,'window:e');
assert.equal(A.veldoraFind(apps,'Kitty.desktop').id,'kitty');
assert.equal(A.veldoraFind(apps,'unknown'),null);
console.log('Veldora event privacy, expiration, limits, priority and app grouping checks passed.');
