// Generated by scripts/generate-theme.py; edit shell/theme/tokens.json.
var colors = {"canvas": "#07090D", "surface": "#11151C", "raised": "#1A202B", "text": "#E8EEF5", "secondary": "#A4AFBE", "accent": "#52D6E8", "ember": "#E76D68", "border": "#36404E", "critical": "#F06A78", "success": "#72D6A0", "warning": "#F0BC67"};
