background {
    color = rgba(08070aff)
}
input-field {
    monitor =
    size = 280, 50
    position = 0, -100
    halign = center
    valign = center
    outer_color = rgba(c8bfd4ff)
    inner_color = rgba(18161eff)
    font_color = rgba(d4d1dbff)
    placeholder_text = Enter password
}
label {
    monitor =
    text = $TIME
    font_size = 60
    color = rgba(d4d1dbff)
    position = 0, 80
    halign = center
    valign = center
}
