-- Generated from veldora-tokens.json by veldora-integrate.py.
hl.env("qsConfig", "veldora")
hl.env("XCURSOR_THEME", "Bibata-Modern-Classic")
hl.env("XCURSOR_SIZE", "24")
hl.config({ general = { border_size = 1, gaps_out = 10, col = { active_border = "rgba(FF8A8F66)", inactive_border = "rgba(00000000)" } }, decoration = { rounding = 16, rounding_power = 2, active_opacity = 1, inactive_opacity = 1, blur = { enabled = true, size = 6, passes = 3 }, shadow = { enabled = true, range = 24, offset = {0, 8}, color = "rgba(00000059)" } } })
hl.layer_rule({ match = { namespace = "^veldora-(top|dock|controls|notifications|osd|launcher)$" }, blur = true, ignore_alpha = 0.5, no_anim = true })
for _, veldora_key in ipairs({"SUPER + SUPER_L", "SUPER + SUPER_R", "SUPER_L", "SUPER_R"}) do hl.unbind(veldora_key) end
hl.bind("Super_L", hl.dsp.exec_cmd("qs -c veldora ipc call veldora launcher"), {release = true, ignore_mods = true, description = "Veldora applications"})
hl.bind("Super_R", hl.dsp.exec_cmd("qs -c veldora ipc call veldora launcher"), {release = true, ignore_mods = true})
hl.unbind("SUPER + A")
hl.bind("SUPER + A", hl.dsp.exec_cmd("qs -c veldora ipc call veldora controls"), {description = "Veldora Control Center"})
hl.unbind("CTRL + SUPER + R")
hl.bind("CTRL + SUPER + R", hl.dsp.exec_cmd("python3 /home/codealpha/Documents/GitHub/VELDORA-OS/veldora-shell/veldora-integrate.py --reload"), {description = "Reload Veldora"})
hl.unbind("XF86AudioRaiseVolume")
hl.bind("XF86AudioRaiseVolume", hl.dsp.exec_cmd("wpctl set-volume -l 1 @DEFAULT_AUDIO_SINK@ 2%+"), {repeating = true, locked = true})
hl.unbind("XF86MonBrightnessUp")
hl.unbind("XF86MonBrightnessDown")
hl.bind("XF86MonBrightnessUp", hl.dsp.exec_cmd("brightnessctl set +5%"), {locked = true})
hl.bind("XF86MonBrightnessDown", hl.dsp.exec_cmd("brightnessctl --min-value=1 set 5%-"), {locked = true})
