#!/usr/bin/env python3
"""Generate desktop color configuration from reviewed Obsidian Storm tokens."""
import json
from pathlib import Path
ROOT = Path(__file__).resolve().parents[1]
THEME = ROOT / 'shell/theme'
t = json.loads((THEME / 'tokens.json').read_text())
(ROOT / 'shell/end4/modules/veldora/theme/TokenData.js').write_text('// Generated by scripts/generate-theme.py; edit shell/theme/tokens.json.\nvar colors = '+json.dumps(t)+';\n')
for preset, accent in [('storm',t['accent']), ('ember',t['ember'])]:
    # Include every upstream M3 color, replacing semantic groups coherently.
    base = json.loads((THEME / 'storm.json').read_text())
    for key in base:
        if key.startswith('surface') or key == 'background': base[key] = t['surface']
        if 'container' in key and not key.startswith('on_'): base[key] = t['raised']
        if key.startswith('on_surface') or key == 'on_background': base[key] = t['text']
    base.update(primary=accent,on_primary=t['canvas'],primary_container=t['raised'],on_primary_container=accent,
                secondary=t['secondary'],on_secondary=t['canvas'],outline=t['secondary'],outline_variant=t['border'],
                surface_tint=accent,error=t['critical'],success=t['success'])
    (THEME / f'{preset}.json').write_text(json.dumps(base,indent=2)+'\n')
    directory=THEME / preset
    directory.mkdir(exist_ok=True)
    (directory / 'foot.ini').write_text(f"[main]\nfont=JetBrains Mono:size=11\n[colors]\nbackground={t['canvas'][1:]}\nforeground={t['text'][1:]}\nregular4={accent[1:]}\nselection-background={t['raised'][1:]}\nselection-foreground={t['text'][1:]}\n")
    (directory / 'gtk.css').write_text(f"@define-color theme_bg_color {t['surface']};\n@define-color theme_fg_color {t['text']};\n@define-color theme_selected_bg_color {accent};\n@define-color theme_selected_fg_color {t['canvas']};\n")
    (directory / 'hyprlock.conf').write_text(f'''# Generated Obsidian Storm lock surface; PAM remains responsible for authentication.
background {{
    monitor =
    color = rgb({t['canvas'][1:]})
}}
input-field {{
    monitor =
    size = 280, 54
    outline_thickness = 2
    outer_color = rgb({accent[1:]})
    inner_color = rgb({t['surface'][1:]})
    font_color = rgb({t['text'][1:]})
    placeholder_text = Password
    position = 0, -80
}}
''')
    fuzzel = (THEME/'fuzzel/fuzzel.ini').read_text()
    import re
    replacements={'background':t['surface'][1:]+'ff','text':t['text'][1:]+'ff','match':accent[1:]+'ff','selection':t['raised'][1:]+'ff','selection-text':t['text'][1:]+'ff','selection-match':accent[1:]+'ff','border':t['border'][1:]+'ff'}
    for key,value in replacements.items(): fuzzel=re.sub(r'^'+key+r'=.*$',key+'='+value,fuzzel,flags=re.M)
    (directory/'fuzzel.ini').write_text(fuzzel)
